FROM node:20-alpine

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install

COPY . .

ENV NEXT_TELEMETRY_DISABLED=1 \
    NODE_ENV=development

RUN npm run build

EXPOSE 3000

CMD ["node_modules/.bin/next", "start"]
