"use client";

import { useRef } from "react";
import { motion, useInView, useReducedMotion } from "framer-motion";
import { Search, ShieldCheck, BrainCircuit, Handshake, Lock } from "lucide-react";

const steps = [
  {
    icon: Search,
    step: "01",
    title: "Discover",
    tagline: "Find properties in plain language",
    description:
      "Message our AI on WhatsApp in Urdu or English. Say 'DHA Lahore 5 marla plot under 1 crore' — AI instantly searches verified listings, filters by your criteria, and sends you top matches with photos and details.",
    example: '"5 marla plot DHA Lahore under 1 crore, near school"',
    color: "#059669",
    lightBg: "bg-emerald-50",
    border: "border-emerald-200",
    textColor: "text-emerald-700",
  },
  {
    icon: ShieldCheck,
    step: "02",
    title: "Verify",
    tagline: "Check any listing in 30 seconds",
    description:
      "Send any listing link, screenshot, or address. Our AI cross-checks ownership records, detects scam patterns, validates documents via OCR, and gives you a plain-language trust report — before you visit or pay anything.",
    example: '"Check this listing for me [link]"',
    color: "#0891B2",
    lightBg: "bg-sky-50",
    border: "border-sky-200",
    textColor: "text-sky-700",
  },
  {
    icon: BrainCircuit,
    step: "03",
    title: "Decide",
    tagline: "AI-powered investment intelligence",
    description:
      "Get a property risk score, investment grade, liquidity rating, 7E tax calculation, CGT estimate, Apna Ghar loan eligibility, and 5-year area growth prediction — all generated by AI and sent to your WhatsApp in seconds.",
    example: '"Should I invest in this property?"',
    color: "#7C3AED",
    lightBg: "bg-violet-50",
    border: "border-violet-200",
    textColor: "text-violet-700",
  },
  {
    icon: Handshake,
    step: "04",
    title: "Connect",
    tagline: "Get matched with a verified agent",
    description:
      "AI qualifies your budget, intent, and location — then matches you with the right KYC-verified agent instantly on WhatsApp. No cold calls, no time wasters. The agent already knows your requirements before they say hello.",
    example: '"Connect me with an agent in Bahria Town"',
    color: "#DB2777",
    lightBg: "bg-pink-50",
    border: "border-pink-200",
    textColor: "text-pink-700",
  },
  {
    icon: Lock,
    step: "05",
    title: "Transact",
    tagline: "Close the deal with full protection",
    description:
      "Lock your deal with a PKR 25K–100K token payment. Get 48-hour exclusivity. Funds are held in Safepay escrow — not by us. Both buyer and seller are protected, and every step is traceable on the platform.",
    example: '"Lock this deal for 48 hours"',
    color: "#D97706",
    lightBg: "bg-amber-50",
    border: "border-amber-200",
    textColor: "text-amber-700",
  },
];

export default function HowItWorks() {
  const ref = useRef(null);
  const inView = useInView(ref, { once: true, margin: "-80px" });
  const prefersReduced = useReducedMotion();

  return (
    <section id="how-it-works" ref={ref} className="bg-gray-950 py-24 px-6">
      <div className="max-w-5xl mx-auto">
        {/* Header */}
        <motion.div
          initial={prefersReduced ? false : { opacity: 0, y: 24 }}
          animate={inView ? { opacity: 1, y: 0 } : {}}
          transition={{ duration: 0.6, ease: "easeOut" }}
          className="text-center mb-16"
        >
          <span className="inline-block bg-white/8 text-emerald-400 border border-white/10 text-xs font-bold uppercase tracking-widest px-4 py-1.5 rounded-full mb-4">
            How It Works
          </span>
          <h2
            className="text-4xl sm:text-5xl font-extrabold text-white leading-tight"
            style={{ fontFamily: "var(--font-cinzel, 'Georgia', serif)" }}
          >
            Five Steps from Search
            <br />
            <span className="bg-gradient-to-r from-emerald-400 to-teal-300 bg-clip-text text-transparent">
              to Signed Deal.
            </span>
          </h2>
          <p className="mt-4 text-gray-400 text-lg max-w-xl mx-auto leading-relaxed">
            Everything happens on WhatsApp — your AI assistant guides you through every step.
          </p>
        </motion.div>

        {/* Steps */}
        <div className="flex flex-col gap-5">
          {steps.map(({ icon: Icon, step, title, tagline, description, example, color, lightBg, border, textColor }, i) => (
            <motion.div
              key={step}
              initial={prefersReduced ? false : { opacity: 0, x: i % 2 === 0 ? -24 : 24 }}
              animate={inView ? { opacity: 1, x: 0 } : {}}
              transition={{ duration: 0.55, delay: prefersReduced ? 0 : i * 0.1, ease: "easeOut" }}
              className="group relative bg-white/5 hover:bg-white/8 border border-white/10 rounded-2xl p-6 transition-colors duration-200 flex flex-col sm:flex-row gap-6 items-start"
            >
              {/* Step number + icon */}
              <div className="flex items-center gap-4 sm:flex-col sm:items-center sm:gap-2 sm:w-20 shrink-0">
                <div
                  className="w-14 h-14 rounded-2xl flex items-center justify-center shrink-0"
                  style={{ backgroundColor: color + "25", border: `1px solid ${color}40` }}
                >
                  <Icon size={24} style={{ color }} />
                </div>
                <div className="text-xs font-bold text-gray-500 tracking-widest sm:text-center">{step}</div>
              </div>

              {/* Content */}
              <div className="flex-1 flex flex-col gap-3">
                <div>
                  <h3 className="text-lg font-bold text-white leading-tight">{title}</h3>
                  <p className="text-sm font-medium mt-0.5" style={{ color }}>{tagline}</p>
                </div>
                <p className="text-sm text-gray-400 leading-relaxed">{description}</p>

                {/* WhatsApp example */}
                <div className="flex items-start gap-2 mt-1">
                  <svg viewBox="0 0 24 24" fill="#25D366" className="w-4 h-4 mt-0.5 shrink-0">
                    <path d="M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.298-.347.446-.52.149-.174.198-.298.298-.497.099-.198.05-.371-.025-.52-.075-.149-.669-1.612-.916-2.207-.242-.579-.487-.5-.669-.51-.173-.008-.371-.01-.57-.01-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.077 4.487.709.306 1.262.489 1.694.625.712.227 1.36.195 1.871.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413-.074-.124-.272-.198-.57-.347m-5.421 7.403h-.004a9.87 9.87 0 01-5.031-1.378l-.361-.214-3.741.982.998-3.648-.235-.374a9.86 9.86 0 01-1.51-5.26c.001-5.45 4.436-9.884 9.888-9.884 2.64 0 5.122 1.03 6.988 2.898a9.825 9.825 0 012.893 6.994c-.003 5.45-4.437 9.884-9.885 9.884m8.413-18.297A11.815 11.815 0 0012.05 0C5.495 0 .16 5.335.157 11.892c0 2.096.547 4.142 1.588 5.945L.057 24l6.305-1.654a11.882 11.882 0 005.683 1.448h.005c6.554 0 11.89-5.335 11.893-11.893a11.821 11.821 0 00-3.48-8.413Z" />
                  </svg>
                  <div className={`text-xs ${lightBg} ${border} border ${textColor} rounded-lg px-3 py-1.5 font-mono italic`}>
                    {example}
                  </div>
                </div>
              </div>

              {/* Hover accent line */}
              <div
                className="absolute left-0 top-4 bottom-4 w-0.5 rounded-full opacity-0 group-hover:opacity-100 transition-opacity duration-200"
                style={{ backgroundColor: color }}
              />
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
}
